#!/usr/bin/env bash
# Runs nginx as nginx and let's it listen on all active IPs on port 8080
chown root:nginx /etc/nginx/nginx.conf
chmod 640 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx /usr/sbin/nginx


